apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: '993397683587.dkr.ecr.ap-south-1.amazonaws.com/test:latest'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: default
  labels:
    name: test1
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
      protocol: TCP
  selector:
    app: test1
  type: NodePort
